### ISSUE TITLE
gzip panics intermittently

### ISSUE THREAD

**Issue by hashbender** [LuxorLabs/Sia#2]
```
2018/01/08 03:18:50 http: panic serving 54.167.135.146:32852: runtime error: index out of range
goroutine 12191 [running]:
net/http.(*conn).serve.func1(0xc4200be5a0)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xa3dc40, 0xee18f0)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
compress/flate.(*huffmanBitWriter).indexTokens(0xc4201ac1e0, 0xc42061e000, 0x5e4d, 0x7000, 0xc420eb4a48, 0x619522)
	/usr/lib/go-1.8/src/compress/flate/huffman_bit_writer.go:559 +0x288
compress/flate.(*huffmanBitWriter).writeBlock(0xc4201ac1e0, 0xc42061e000, 0x5e4d, 0x7000, 0x0, 0xc420acb173, 0x6e8d, 0x6e8d)
	/usr/lib/go-1.8/src/compress/flate/huffman_bit_writer.go:448 +0xa3
compress/flate.(*compressor).writeBlock(0xc421282000, 0xc42061e000, 0x5e4c, 0x7000, 0x10000, 0xda, 0x41c)
	/usr/lib/go-1.8/src/compress/flate/deflate.go:170 +0xc4
compress/flate.(*compressor).deflate(0xc421282000)
	/usr/lib/go-1.8/src/compress/flate/deflate.go:415 +0xa6a
compress/flate.(*compressor).close(0xc421282000, 0x0, 0x0)
	/usr/lib/go-1.8/src/compress/flate/deflate.go:643 +0x50
compress/flate.(*Writer).Close(0xc421282000, 0xb23e18, 0xc420eb4b88)
	/usr/lib/go-1.8/src/compress/flate/deflate.go:729 +0x2d
compress/gzip.(*Writer).Close(0xc426820000, 0xc426820000, 0x0)
	/usr/lib/go-1.8/src/compress/gzip/gzip.go:241 +0x6c
github.com/gorilla/handlers.CompressHandlerLevel.func1(0xe0e1a0, 0xc4201dc000, 0xc4213aa000)
	/home/luxor/Go/src/github.com/gorilla/handlers/compress.go:147 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc4203c8740, 0xe0e1a0, 0xc4201dc000, 0xc4213aa000)
	/usr/lib/go-1.8/src/net/http/server.go:1942 +0x44
github.com/NebulousLabs/Sia/api.(*API).ServeHTTP(0xc4200c0180, 0xe0e1a0, 0xc4201dc000, 0xc4213aa000)
	/home/luxor/Go/src/github.com/NebulousLabs/Sia/api/api.go:176 +0x58
net/http.(*ServeMux).ServeHTTP(0xc4200f3ad0, 0xe0e1a0, 0xc4201dc000, 0xc4213aa000)
	/usr/lib/go-1.8/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420086c60, 0xe0e1a0, 0xc4201dc000, 0xc4213aa000)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4200be5a0, 0xe0ebe0, 0xc420a5e280)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
```

**Comment by hashbender** [comment]
This is related to https://github.com/golang/go/issues/18883
